[project]
name = "mcp-data-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.1",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "psutil>=7.0.0",
]
